apiVersion: dataplane.openstack.org/v1beta1
kind: OpenStackDataPlaneNodeSet
metadata:
  name: compute-2
spec:
  tlsEnabled: false
  env:
    - name: ANSIBLE_FORCE_COLOR
      value: "True"
    - name: ANSIBLE_VERBOSITY
      value: "2"
  services:
    - bootstrap
    - download-cache
    - configure-network
    - validate-network
    - install-os
    - configure-os
    - ssh-known-hosts
    - run-os
    - reboot-os
    - install-certs
    - libvirt
    - nova
    - ovn
    - neutron-metadata
    - telemetry
  preProvisioned: true
  nodes:
      edpm-compute-2:
        hostName: compute02.localdomain
        ansible:
          ansibleHost: 172.22.0.110
        networks:
        - name: ctlplane
          subnetName: subnet1
          defaultRoute: false
          fixedIP: 172.22.0.110
        - name: internalapi
          subnetName: subnet1
          fixedIP: 172.17.0.110
        - name: storage
          subnetName: subnet1
          fixedIP: 172.18.0.110
        - name: tenant
          subnetName: subnet1
          fixedIP: 172.19.0.110
        - name: external
          subnetName: subnet1
          fixedIP: 172.21.0.110
  nodeTemplate:
    ansibleSSHPrivateKeySecret: dataplane-ansible-ssh-private-key-secret
    ansible:
      ansibleUser: cloud-user
      ansibleVarsFrom:
      - prefix: subscription_manager_
        secretRef:
          name: subscription-manager
      - secretRef:
          name: redhat-registry
      ansibleVars:
         edpm_network_config_template: |
           ---
           {% set mtu_list = [ctlplane_mtu] %}
           {% for network in nodeset_networks %}
           {{ mtu_list.append(lookup('vars', networks_lower[network] ~ '_mtu')) }}
           {%- endfor %}
           {% set min_viable_mtu = mtu_list | max %}
           network_config:
           - type: interface
             name: eth1
             mtu: {{ ctlplane_mtu }}
             dns_servers: {{ ctlplane_dns_nameservers }}
             domain: {{ dns_search_domains }}
             use_dhcp: false
             addresses:
             - ip_netmask: {{ ctlplane_ip }}/{{ ctlplane_cidr }}           
           - type: interface
             name: eth2
             mtu: {{ internalapi_mtu }}
             use_dhcp: false
             addresses:
             - ip_netmask:
                 {{ internalapi_ip }}/{{ internalapi_cidr }}
             routes: {{ internalapi_host_routes }}
           - type: interface
             name: eth3
             mtu: {{ min_viable_mtu }}
             use_dhcp: false
             addresses:
             - ip_netmask:
                 {{ storage_ip }}/{{ storage_cidr }}
             routes: {{ storage_host_routes }}
           - type: interface
             name: eth4
             mtu: {{ tenant_mtu }}
             use_dhcp: false
             addresses:
             - ip_netmask:
                 {{ tenant_ip }}/{{ tenant_cidr }}
             routes: {{ tenant_host_routes }}
           - type: ovs_bridge
             name: br-ex
             mtu: 1500
             use_dhcp: false
             addresses:
             - ip_netmask:
                {{ external_ip }}/{{ external_cidr }}
             members:
             - type: interface
               name: eth5
               mtu: 1500
               # force the MAC address of the bridge to this interface
               primary: true
          
         edpm_network_config_hide_sensitive_logs: false
         #
         # These vars are for the network config templates themselves and are
         # considered EDPM network defaults (for all computes).
         ctlplane_host_routes: []
         ctlplane_subnet_cidr: 24
         dns_search_domains: localdomain
         ctlplane_mtu: 1500
         external_mtu: 1500
         external_cidr: '24'
         external_host_routes: []
         internalapi_mtu: 1500
         internalapi_cidr: '24'
         internalapi_host_routes: []
         storage_mtu: 1500
         storage_cidr: '24'
         storage_host_routes: []
         tenant_mtu: 1500
         tenant_cidr: '24'
         tenant_host_routes: []

         # EDPM network defaults
         neutron_physical_bridge_name: br-ex
         neutron_public_interface_name: eth0

         # edpm ovn-controller configuratio
         edpm_ovn_bridge_mappings: ["datacentre:br-ex"]
         edpm_ovn_bridge: br-int
         edpm_ovn_encap_type: geneve
         ovn_monitor_all: true
         edpm_ovn_remote_probe_interval: 60000
         edpm_ovn_ofctrl_wait_before_clear: 8000

         # edpm_nodes_validation
         edpm_nodes_validation_validate_controllers_icmp: false
         edpm_nodes_validation_validate_gateway_icmp: false
         gather_facts: false
         enable_debug: false
         
         # Do not attempt OVS major upgrades here
         edpm_ovs_packages:
         - openvswitch3.1

         edpm_bootstrap_release_version_package: []

         edpm_bootstrap_command: |
           subscription-manager register --username "{{ subscription_manager_username }}" --password "{{ subscription_manager_password }}"
           sudo subscription-manager release --set=9.4
           sudo subscription-manager repos --disable=*
           sudo subscription-manager repos --enable=rhel-9-for-x86_64-baseos-eus-rpms --enable=rhel-9-for-x86_64-appstream-eus-rpms --enable=rhel-9-for-x86_64-highavailability-eus-rpms --enable=fast-datapath-for-rhel-9-x86_64-rpms --enable=rhoso-18.0-for-rhel-9-x86_64-rpms --enable=rhceph-7-tools-for-rhel-9-x86_64-rpms
           dnf -y upgrade openstack-selinux
           rm -f /run/virtlogd.pid